# Generated by Django 5.0.3 on 2024-03-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theatre", "0002_actor_genre_play_performance_reservation_ticket"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
