# Generated by Django 5.0.3 on 2024-03-28 10:06

import theatre
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theatre", "0003_alter_reservation_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="genre",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="performance",
            options={"ordering": ["show_time"]},
        ),
        migrations.AlterModelOptions(
            name="reservation",
            options={"ordering": ["created_at"]},
        ),
        migrations.AlterModelOptions(
            name="ticket",
            options={"ordering": ["row", "seat"]},
        ),
        migrations.AddField(
            model_name="play",
            name="image",
            field=models.ImageField(
                null=True, upload_to=theatre.models.movie_image_file_path
            ),
        ),
        migrations.AlterField(
            model_name="play",
            name="actors",
            field=models.ManyToManyField(
                related_name="plays", to="theatre.actor"
            ),
        ),
        migrations.AlterField(
            model_name="play",
            name="genres",
            field=models.ManyToManyField(
                related_name="plays", to="theatre.genre"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together={("performance", "row", "seat")},
        ),
    ]
