# Generated by Django 5.0.3 on 2024-03-28 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "theatre",
            "0004_alter_genre_options_alter_performance_options_and_more"
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="performance",
            name="play",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="theatre.play",
            ),
        ),
    ]
